### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by vladrip** [vladrip/drgassistant#5]
- [ ] Rework app structure to make it more fragment-oriented. Make BuildActivity a fragment, so user could use wiki while editing a build, and MultiChoiceActivity so it could access builds from MainActivity. That way build list can be moved from DrgApp to MainActivity as well. Absolutely get rid of DrgBaseFragment.getPersistentView hack, support back stack.
- [ ] Replace slow and not safe getInstance with obtainTypedArray. Create typed array in arrays.xml and map all drawable names to their ids. Quite a monotone and long work, but maybe there is some script that can generate it himself. 
- [ ] Add links for all BuildItems, maybe as a button to the right of their icons.
- [ ] #3
